### ISSUE TITLE
Question: Modifying item slot widget

### ISSUE THREAD

**Issue by MiraculixxT** [AjjMC/ajjgui#4]
I try to create an automated UI that allows input and for example transform this input into something different after a certain time. To my knowledge, I need to change the NBT of the marker and perform a reload after doing so, but this results into invalid interactions and a broken UI.

Selector: `@n[type=marker,tag=ajjgui.gui_origin]`
Commands:
```yml
# Clearing top item slot 
data modify entity @s data.gui[0][{Slot:11}] merge value {id:"minecraft:structure_void",components:{"minecraft:custom_model_data":20,"minecraft:custom_data":{ajjgui:{state:0}}}}
data modify entity @s data.gui[0][{Slot:15}] merge value {id:"minecraft:structure_void",components:{"minecraft:custom_model_data":20,"minecraft:custom_data":{ajjgui:{state:0}}}}

# Set item in bottom item slot
$data modify entity @s data.gui[0][{Slot:22}] merge value {id:"minecraft:$(type)", components:{"minecraft:custom_data":{chapter3.lab:1b,NoDrop:1b,ajjgui:{state:1}},"minecraft:hide_tooltip":{}}}
function ajjgui:_reload
```

The function above is triggered as soon as the process is ready and the yellow glass disappears.
Mockup UI, black squares are inputs
![grafik](https://github.com/user-attachments/assets/aaaae154-8ec4-4fed-9f6a-bee8cd33ac10)
Interaction Video: https://github.com/user-attachments/assets/21c4a658-6bfc-4815-ba85-d8671a33a95c

**Comment by AjjMC** [comment]
The problem is that you are using an Int data type for `Slot` (e.g., `Slot:11`) instead of a Byte (e.g., `Slot:11b`) as the marker does not correct data types automatically. Once you change that and recompile the GUI, it should work.

**Comment by MiraculixxT** [comment]
Thank you a lot! What a silly overside from me... 

Btw, in the [modify value section](https://github.com/AjjMC/ajjgui?tab=readme-ov-file#examples-7), the examples still have the capitalized GUI path instead of the now used lowercase gui path

**Comment by AjjMC** [comment]
I fixed it. Thank you!
